Spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 150460
    database: 0
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: -1 #-1表示没有限制
        max-wait: -1ms
    timeout: 10000ms
server:
  port: 8086